[server]
scriptfile = "script.py"
root = "files"
address = "0.0.0.0"
port = 6969
timeout = 5
retries = 3

[env]
ramvar = "baseaddr"
cmdtftp = "tftpboot"
cmdtftpput = "tftpput"

[cam123]
script = "camera_bootstrap"

[default]
script = "default"
